name       : icoutils
version    : 0.31.3
release    : 4
source     :
    - https://download.savannah.gnu.org/releases/icoutils/icoutils-0.31.3.tar.bz2 : d4651de8e3f9e28d24b5343a2b7564f49754e5fe7d211c5d4dd60dcd65c8a152
license    : GPL-3.0
component  : system.utils
summary    : Icon and Cursor Utils
description: |
    The icoutils are a set of program for extracting and converting images in Microsoft Windows(R) icon and cursor files. These files usually have the extension .ico or .cur, but they can also be embedded in executables and libraries (.dll-files).
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
