name       : icoutils
version    : 0.31.1
release    : 2
source     :
    - http://ftp.yzu.edu.tw/nongnu/icoutils/icoutils-0.31.1.tar.bz2 : 26e29d3c78f25d4cdf402501ac0414c51a9a092daebf6c9dee3b837dee693093
license    : GPL-3.0
component  : system.utils
summary    : Icon and Cursor Utils
description: |
    The icoutils are a set of program for extracting and converting images in Microsoft Windows(R) icon and cursor files. These files usually have the extension .ico or .cur, but they can also be embedded in executables and libraries (.dll-files).
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
