name       : icoutils
version    : 0.31.2
release    : 3
source     :
    - http://savannah.nongnu.org/download/icoutils/icoutils-0.31.2.tar.bz2 : 14155eb22e7531ed449a822a3e94df511a36b75273fcece75a37794ed3e34be0
license    : GPL-3.0
component  : system.utils
summary    : Icon and Cursor Utils
description: |
    The icoutils are a set of program for extracting and converting images in Microsoft Windows(R) icon and cursor files. These files usually have the extension .ico or .cur, but they can also be embedded in executables and libraries (.dll-files).
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
