name       : icoutils
version    : 0.32.0
release    : 5
source     :
    - https://download.savannah.gnu.org/releases/icoutils/icoutils-0.32.0.tar.bz2 : 17234d6e922f5dcd2dc8351a4b3535a2f348bb9b92c17ca3e438132147019ca6
license    : GPL-3.0
component  : system.utils
summary    : Icon and Cursor Utils
description: |
    The icoutils are a set of program for extracting and converting images in Microsoft Windows(R) icon and cursor files. These files usually have the extension .ico or .cur, but they can also be embedded in executables and libraries (.dll-files).
builddeps  :
    - pkgconfig(libpng)
setup      : |
    %configure
build      : |
    %make
install    : |
    %make_install
